apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: echo-http
  namespace: echo-http
spec:
  gatewayClassName: eg
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: echo-http.sandbox.k8s.phl.io
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - name: echo-http-gw-tls
        mode: Terminate
