apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/instance: choose-native-plants
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: choose-native-plants
    app.kubernetes.io/version: 2.0.6
    helm.sh/chart: choose-native-plants-2.0.6
  name: choose-native-plants
  namespace: choose-native-plants
spec:
  rules:
    - host: choose-native-plants.sandbox.k8s.phl.io
      http:
        paths:
          - backend:
              service:
                name: choose-native-plants
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - choose-native-plants.sandbox.k8s.phl.io
      secretName: choose-native-plants-tls
