apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-cluster
  namespace: cloudnative-pg
spec:
  imageName: ghcr.io/cloudnative-pg/postgis:18-3-system-trixie
  instances: 2
  managed:
    roles:
      - login: true
        name: balancer
        passwordSecret:
          name: balancer-db-credentials
  storage:
    size: 20Gi
