backend:
  image:
    tag: 0.3.2
frontend:
  image:
    tag: 0.3.2
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: prevention-point.sandbox.k8s.phl.io
      paths: [ '/' ]
  tls:
    - secretName: prevention-point-tls
      hosts:
        - prevention-point.sandbox.k8s.phl.io