apiVersion: v1
data:
  DATABASE: postgres
  DEBUG: 'FALSE'
  DJANGO_ALLOWED_HOSTS: 'frontend localhost 127.0.0.1 [::1]'
  EMAIL_HOST: smtp.gmail.com
  EMAIL_HOST_USER: balancer-noreply@gmail.com
  EMAIL_PORT: '587'
  LOGIN_REDIRECT_URL: 'https://balancertestsite.com/login'
  SQL_ENGINE: django.db.backends.postgresql
  SQL_PORT: '5432'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: backend-env
  namespace: balancer
