apiVersion: v1
data:
  DEBUG: 'true'
  LOGIN_REDIRECT_URL: ''
  REACT_APP_API_BASE_URL: https://balancer.sandbox.k8s.phl.io/
  SQL_DATABASE: balancer
  SQL_ENGINE: django.db.backends.postgresql
  SQL_HOST: shared-cluster-rw.cloudnative-pg.svc.cluster.local
  SQL_PORT: '5432'
  SQL_USER: balancer
kind: ConfigMap
metadata:
  name: balancer-config
  namespace: balancer
