apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: 'pre-install,pre-upgrade'
    helm.sh/hook-delete-policy: 'before-hook-creation,hook-succeeded'
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.34.1
    helm.sh/chart: ingress-nginx-2.11.1
  name: ingress-nginx-admission-create
  namespace: ingress-nginx
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admission-webhook
        app.kubernetes.io/instance: ingress-nginx
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/version: 0.34.1
        helm.sh/chart: ingress-nginx-2.11.1
      name: ingress-nginx-admission-create
    spec:
      containers:
        - args:
            - create
            - >-
              --host=ingress-nginx-controller-admission,ingress-nginx-controller-admission.ingress-nginx.svc
            - '--namespace=ingress-nginx'
            - '--secret-name=ingress-nginx-admission'
          image: 'docker.io/jettech/kube-webhook-certgen:v1.2.2'
          imagePullPolicy: IfNotPresent
          name: create
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: ingress-nginx-admission
