apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: envoy-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v1.7.3
    helm.sh/chart: gateway-helm-v1.7.3
  name: envoy-gateway
  namespace: envoy-gateway-system
