apiVersion: v1
kind: Namespace
metadata:
  name: echo-http

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: echo-http
  namespace: echo-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-http
  template:
    metadata:
      labels:
        app: echo-http
    spec:
      containers:
        - name: echo-http
          image: mendhak/http-https-echo:17

---

kind: Service
apiVersion: v1
metadata:
  name: echo-http
  namespace: echo-http
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: echo-http

---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: echo-http
  namespace: echo-http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - echo-http.sandbox.k8s.phl.io
      secretName: echo-http-tls
  rules:
    - host: echo-http.sandbox.k8s.phl.io
      http:
        paths:
          - path: /
            backend:
              serviceName: echo-http
              servicePort: 80
