apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: balancer
  namespace: flux-system
spec:
  image: ghcr.io/codeforphilly/balancer-main/app
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: balancer
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: balancer
  policy:
    semver:
      range: '>=1.2.0-0' # Includes pre-releases like 1.2.0-dev.TIMESTAMP

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: balancer-updates
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: 'App: balancer image update to {{ .SelectedTarget.Tag }}'
    push:
      branch: main
  update:
    path: ./balancer
    strategy: Setters
