apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hairpin-proxy-controller
  name: hairpin-proxy-controller
  namespace: hairpin-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hairpin-proxy-controller
  template:
    metadata:
      labels:
        app: hairpin-proxy-controller
    spec:
      containers:
        - image: 'compumike/hairpin-proxy-controller:0.2.1'
          name: main
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
      securityContext:
        runAsGroup: 65533
        runAsUser: 405
      serviceAccountName: hairpin-proxy-controller-sa
