apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: prometheus
    chart: prometheus-13.0.0
    component: pushgateway
    heritage: Helm
    release: prometheus
  name: prometheus-pushgateway
rules: []
