apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: linode-cnpg
  namespace: cloudnative-pg
spec:
  configuration:
    data:
      compression: gzip
    destinationPath: s3://cfp-sandbox-cluster-cnpg/
    endpointURL: https://us-east-1.linodeobjects.com
    s3Credentials:
      accessKeyId:
        key: ACCESS_KEY_ID
        name: cnpg-backup-creds
      secretAccessKey:
        key: ACCESS_SECRET_KEY
        name: cnpg-backup-creds
    wal:
      compression: gzip
  retentionPolicy: 30d
