apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hairpin-proxy-controller-r
  namespace: kube-system
rules:
  - apiGroups:
      - ''
    resourceNames:
      - coredns
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - update
