apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: paws-data-pipeline
  namespace: paws-data-pipeline
spec:
  gatewayClassName: eg
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: paws-data-pipeline.sandbox.k8s.phl.io
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - name: paws-data-pipeline-gw-tls
        mode: Terminate
