ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: paws-data-pipeline.sandbox.k8s.phl.io
      paths: [ '/' ]
  tls:
    - secretName: paws-data-pipeline-tls
      hosts:
        - paws-data-pipeline.sandbox.k8s.phl.io
