apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: choose-native-plants
  namespace: choose-native-plants
spec:
  gatewayClassName: eg
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: choose-native-plants.sandbox.k8s.phl.io
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - name: choose-native-plants-gw-tls
        mode: Terminate
