apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-admin
  namespace: choose-native-plants
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
      - delete
  - apiGroups:
      - ''
    resources:
      - pods/exec
      - pods/portforward
    verbs:
      - create
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
