apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: metabase
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    name: database
  type: ClusterIP
