apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase
spec:
  ports:
    - name: metabase-http
      port: 3000
      targetPort: 3000
  selector:
    name: metabase
  type: ClusterIP
