apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeforphilly-data
  namespace: codeforphilly-rewrite-sandbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain
