apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: choose-native-plants
    app.kubernetes.io/name: choose-native-plants
  name: choose-native-plants-mongo-data
  namespace: choose-native-plants
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain
