apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: db
  name: db
  namespace: balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: db
  serviceName: db
  template:
    metadata:
      labels:
        app.kubernetes.io/component: db
        io.kompose.network/balancer-main-default: 'true'
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: postgresql
          image: 'postgres:15'
          name: db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
              subPath: data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-claim
