apiVersion: v1
kind: Namespace
metadata:
  name: choose-native-plants

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-admin
  namespace: choose-native-plants

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-admin
  namespace: choose-native-plants
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/portforward"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-admin
  namespace: choose-native-plants
subjects:
- kind: ServiceAccount
  name: deployment-admin
  namespace: choose-native-plants
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-admin
