apiVersion: v1
kind: Namespace
metadata:
  name: choose-native-plants

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-admin
  namespace: choose-native-plants

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-admin
  namespace: choose-native-plants
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/portforward", "pods/log"]
  verbs: ["create", "get", "list"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["helm.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-admin
  namespace: choose-native-plants
subjects:
- kind: ServiceAccount
  name: deployment-admin
  namespace: choose-native-plants
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-admin
