apiVersion: v1
kind: Namespace
metadata:
  name: paws-data-pipeline

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-admin
  namespace: paws-data-pipeline

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-admin
  namespace: paws-data-pipeline
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/portforward", "pods/log"]
  verbs: ["create"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-admin
  namespace: paws-data-pipeline
subjects:
- kind: ServiceAccount
  name: deployment-admin
  namespace: paws-data-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-admin
