apiVersion: v1
kind: Service
metadata:
  labels:
    app: balancer
  name: balancer
  namespace: balancer
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: balancer
