# These values as applied last as downstream overrides
# See https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - sealed-secrets.sandbox.k8s.phl.io
  tls:
    - secretName: sealed-secrets-tls
      hosts:
        - sealed-secrets.sandbox.k8s.phl.io

dashboards:
  create: true
