apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
  labels:
    app.kubernetes.io/instance: paws-data-pipeline
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: paws-datapipeline
    app.kubernetes.io/version: 0.8.0
    helm.sh/chart: paws-datapipeline-0.1.0
  name: paws-dp-chart
  namespace: paws-data-pipeline
spec:
  rules:
    - host: paws-data-pipeline.sandbox.k8s.phl.io
      http:
        paths:
          - backend:
              service:
                name: paws-dp-chart
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: test.pawsdp.org
      http:
        paths:
          - backend:
              service:
                name: paws-dp-chart
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - paws-data-pipeline.sandbox.k8s.phl.io
        - test.pawsdp.org
      secretName: paws-data-pipeline-tls
