apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/instance: paws-data-pipeline
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: paws-datapipeline
    app.kubernetes.io/version: 0.8.0
    helm.sh/chart: paws-datapipeline-0.1.0
  name: paws-dp-chart
  namespace: paws-data-pipeline
spec:
  rules:
    - host: paws-data-pipeline.sandbox.k8s.phl.io
      http:
        paths:
          - backend:
              serviceName: paws-dp-chart
              servicePort: 80
            path: /
  tls:
    - hosts:
        - paws-data-pipeline.sandbox.k8s.phl.io
      secretName: paws-data-pipeline-tls
