apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: barman-cloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plugin-barman-cloud
    app.kubernetes.io/version: v0.15.0
    helm.sh/chart: plugin-barman-cloud-0.8.0
  name: barman-cloud-plugin-barman-cloud
  namespace: cloudnative-pg
