apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
    chart: loki-2.10.1
    heritage: Helm
    release: loki
    variant: headless
  name: loki-headless
  namespace: loki
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
  selector:
    app: loki
    release: loki
