apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: loki
    chart: loki-2.16.0
    heritage: Helm
    release: loki
  name: loki
  namespace: loki
spec:
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
  selector:
    app: loki
    release: loki
  type: ClusterIP
