apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: deployment-admin
  namespace: paws-data-pipeline
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ''
    resources:
      - pods/exec
      - pods/portforward
      - pods/log
    verbs:
      - create
