app:
  image:
    tag: "2.0.5"
  env:
    - name: NODE_OPTIONS
      value: "--openssl-legacy-provider --max-old-space-size=768"
  envFrom:
    - secretRef:
        name: linode-storage

# Resource settings for the application
resources:
  limits:
    memory: 4Gi
  requests:
    memory: 1Gi

# Allow the Helm chart to create PVCs automatically
# (removed existingPVCs configuration)

# Allow the Helm chart to create Service and Ingress resources automatically
# (removed existingService and existingIngress configuration)

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: choose-native-plants.sandbox.k8s.phl.io
      paths: [ '/' ]
  tls:
    - secretName: choose-native-plants-tls
      hosts:
        - choose-native-plants.sandbox.k8s.phl.io
