app:
  image:
    tag: "2.0.3"
  env:
    - name: PAC_API_BASE_URL
      valueFrom:
        secretKeyRef:
          name: pac-api
          key: PAC_API_BASE_URL
          optional: false
    - name: PAC_API_KEY
      valueFrom:
        secretKeyRef:
          name: pac-api
          key: PAC_API_KEY
          optional: false
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: linode-storage
          key: AWS_ACCESS_KEY_ID
          optional: false
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: linode-storage
          key: AWS_SECRET_ACCESS_KEY
          optional: false
    - name: AWS_DEFAULT_REGION
      valueFrom:
        secretKeyRef:
          name: linode-storage
          key: AWS_DEFAULT_REGION
          optional: false
    - name: LINODE_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: linode-storage
          key: LINODE_BUCKET_NAME
          optional: false
    - name: LINODE_ENDPOINT_URL
      valueFrom:
        secretKeyRef:
          name: linode-storage
          key: LINODE_ENDPOINT_URL
          optional: false
    - name: NODE_OPTIONS
      value: "--openssl-legacy-provider --max-old-space-size=768"

# Resource settings for the application
resources:
  limits:
    memory: 4Gi
  requests:
    memory: 1Gi

# Use existing resources instead of creating new ones
existingPVCs:
  appImages: "choose-native-plants-app-images-v2"
  mongoData: "choose-native-plants-mongo-data"

# Use existing service and ingress
existingService: true
existingIngress: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: choose-native-plants.sandbox.k8s.phl.io
      paths: [ '/' ]
  tls:
    - secretName: choose-native-plants-tls
      hosts:
        - choose-native-plants.sandbox.k8s.phl.io
