app:
  image:
    tag: "2.0.2"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: choose-native-plants.sandbox.k8s.phl.io
      paths: [ '/' ]
  tls:
    - secretName: choose-native-plants-tls
      hosts:
        - choose-native-plants.sandbox.k8s.phl.io
