apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-backup-creds
  namespace: cloudnative-pg
spec:
  encryptedData:
    ACCESS_KEY_ID: >-
      AgA41kwiQyT4KatYF1VR3iXF3QEFwPaGHhhNSZGKdPFzKAsf8F1zCJwJ01cig/C/UMRLPWg0wsIy4wjpXFNBodkt5qUoXcBHI4TkCs9op9V4b1BAkThG9gxVbKxVbTk6ydNCGvGBciyjLINTMQ2K2HXVigKPOJbiOgVIgHTFPCWk51m5SOUURpkGqaIevIU3TN1oH5iy4iR0pEml7CClpsR3M105Yi7ZfWpp+0O+3MnC/zPWtiHk24cm9XheEgk/YDrWj1ZmWu50jzFCEXAdlVIlT3reI3igSNmxAs5sdRM+x41qeJXyoRb2vGIbmcWOQ/+SQqRLlRTMx/dd6GdO6krV6ZPAeX+1S+ONUb7ORc9VJdECFX3zOQYf7D9QcMTgsiy/zMZKW0Ni55aRM06ONoDhYrFVcJxiRO3VLPObZK9V9yq7ZAdtn45Wz2qfEB+nm+kRhIoLqRObxageFjmDHnfUP9hJ6qNA7PhpNatDS16ieU0CBZI7uVTH/k2uUHfCtNAdB73u7oGxqd5P1Vy2DVX0W0aOXqvwvUvfx7cER/2PGc6pD0vc6aZguoc9hGXQ4qZSDeVBOlsdEb09Iy6oIyLF3osAU+MaftDVa2zHCbQFFSmvmCFklqv2qRgNNPy86oGWBfV6iZHGmQNyP/Uml6Go0/XwrDBSyVB6qSjOQ7ZRcDmplNzlHKJ95r9uNVkCvY0wBY/x+yw0cdjVEZuvp8UT2Vx/fQ==
    ACCESS_SECRET_KEY: >-
      AgAGJ76ft3nVlnGtTRoDFfpZvzW38ksdCdTohiXzBjRSytatoU0O66xy6Qf4FXkhGxH2x7nJxAzmE4efnByiOFbLhWhilgUNIo9w6IM6WrfozZQAHWtBdZXxYyo/Hg9SqvA9ky7lHZ5E9n9eSVcZ8wzsAn6vnNUTRlHk6+d8RI72AN0g971MSUABble8yhgnTb1gGLKZyg2B1tiy6Y7ZmzUHQizIfqAVn1yYO4CZB6EoGSxj3cm9uzWrLxcZseu50A0+U+KAQ1Tic15g1doQtO+i8r2Z08re2q1CAXxNSwgPKzfwSwe2AoGIIEYfJr45DoLQeIP7S2uLJwHPe06z28aNCw+orgXTHqh7b2rewcLn4ME0pOafAXr5JKu7xZHX10/h0PUr1/fGP79R1seaWNSs/kmBwmzNeG2+BSTUM8dc8+aSqIV+plIN/kBaVPQQr5alDS477AHSjErW5E247WTx0KC3g4vy/ySbC8sSP4Y2YJ8HEPzhOgTSB9c8fuUOZAeNejogA07rvCKq4JVVBaI/VSuEn/eTx3Uc8E020Po8sItq9OOiyPsQMLk7wTyMmr4ZgcryyqZKMgNk+Kzg0zqNGVkA2hc7IeRoLcySzIZhJ+T71q0p7sQncYu36iiAXs5MO8Zs/LFTApYhhyVmL8Vzp6dCHEDQJRY4MK1EOFe4fIl67RNkEpsixo/+1Ld4qYcmkna7BLwNN6WeaKu/x7ElAgZ1DbCZEjj6KfFgiFBZ0KWETPLrMXcl
  template:
    metadata:
      name: cnpg-backup-creds
      namespace: cloudnative-pg
