apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: choose-native-plants
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: choose-native-plants
    app.kubernetes.io/version: 2.0.5
    helm.sh/chart: choose-native-plants-2.0.5
  name: choose-native-plants
  namespace: choose-native-plants
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app.kubernetes.io/instance: choose-native-plants
    app.kubernetes.io/name: choose-native-plants
  type: NodePort
