apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: choose-native-plants
  namespace: choose-native-plants
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: eg
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: choose-native-plants.sandbox.k8s.phl.io
      tls:
        mode: Terminate
        certificateRefs:
          - name: choose-native-plants-gw-tls
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: choose-native-plants
  namespace: choose-native-plants
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
    - name: choose-native-plants
  hostnames:
    - choose-native-plants.sandbox.k8s.phl.io
  rules:
    - backendRefs:
        - name: choose-native-plants
          port: 80
