apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: prevention-point
  namespace: prevention-point
spec:
  gatewayClassName: eg
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: prevention-point.sandbox.k8s.phl.io
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - name: prevention-point-gw-tls
        mode: Terminate
