apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-cluster
  namespace: cloudnative-pg
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgis:18-3-system-trixie
  storage:
    size: 20Gi

  managed:
    roles:
      - name: balancer
        login: true
        passwordSecret:
          name: balancer-db-credentials
