apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cainjector
    helm.sh/chart: cert-manager-v0.1.0
  name: 'cert-manager-cainjector:leaderelection'
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'cert-manager-cainjector:leaderelection'
subjects:
  - kind: ServiceAccount
    name: cert-manager-cainjector
    namespace: cert-manager
