apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: loki
    chart: loki-2.16.0
    heritage: Helm
    release: loki
  name: loki
  namespace: loki
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - loki
    resources:
      - podsecuritypolicies
    verbs:
      - use
