apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: balancer
  namespace: balancer
spec:
  ingressClassName: nginx
  rules:
    - host: balancer.sandbox.k8s.phl.io
      http:
        paths:
          - backend:
              service:
                name: balancer
                port:
                  number: 8000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - balancer.sandbox.k8s.phl.io
      secretName: balancer-tls
