apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: balancer-ingress
  namespace: balancer
spec:
  rules:
    - host: balancer.sandbox.k8s.phl.io
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - balancer.sandbox.k8s.phl.io
      secretName: balancer-tls
