apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: paws-data-pipeline
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: paws-datapipeline
    app.kubernetes.io/version: 0.8.0
    helm.sh/chart: paws-datapipeline-0.1.0
  name: paws-dp-chart
  namespace: paws-data-pipeline
