apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: balancer-listeners
  namespace: balancer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  parentRef:
    name: main-gateway
    namespace: envoy-gateway-system
    group: gateway.networking.k8s.io
    kind: Gateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: sandbox.balancerproject.org
      tls:
        mode: Terminate
        certificateRefs:
          - name: balancer-tls
            kind: Secret
