apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: balancer

resources:
  - manifests/overlays/sandbox

images:
  - name: ghcr.io/codeforphilly/balancer-main/app
    newTag: "0.0.0-dev.20260211012449"

patches:
  - target:
      kind: Ingress
      name: balancer
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
      - op: add
        path: /metadata/annotations/kubernetes.io~1ingress.class
        value: nginx
      - op: replace
        path: /spec/tls/0/hosts/0
        value: sandbox.balancerproject.org
      - op: replace
        path: /spec/rules/0/host
        value: sandbox.balancerproject.org
