ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: balancer.sandbox.k8s.phl.io
      paths: ['/']
  tls:
    - secretName: balancer-tls
      hosts:
        - balancer.sandbox.k8s.phl.io
