apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webhook
    helm.sh/chart: cert-manager-v0.1.0
  name: 'cert-manager-webhook:subjectaccessreviews'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'cert-manager-webhook:subjectaccessreviews'
subjects:
  - apiGroup: ''
    kind: ServiceAccount
    name: cert-manager-webhook
    namespace: cert-manager
