apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sealed-secrets-access-choose-native-plants
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealed-secrets-access
subjects:
  - kind: ServiceAccount
    name: deployment-admin
    namespace: choose-native-plants
