apiVersion: v1
kind: Service
metadata:
  name: codeforphilly
  namespace: codeforphilly-rewrite-sandbox
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3001
  selector:
    app.kubernetes.io/name: codeforphilly
  type: ClusterIP
