apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app: prometheus
    chart: prometheus-14.6.1
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-server
  namespace: prometheus
