apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app: prometheus
    chart: prometheus-15.18.0
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-server
  namespace: prometheus
