apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app: prometheus
    chart: prometheus-15.6.0
    component: pushgateway
    heritage: Helm
    release: prometheus
  name: prometheus-pushgateway
  namespace: prometheus
