apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: frontend
  namespace: balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.prod.yml -o helm-chart
        kompose.version: 1.31.2 (a92241f79)
      labels:
        app.kubernetes.io/component: frontend
        io.kompose.network/balancer-main-default: 'true'
    spec:
      containers:
        - image: 'ghcr.io/codeforphilly/balancer-main/frontend:0.1.1'
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf
              readOnly: true
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: nginx-conf
          name: nginx-conf
