apiVersion: v1
kind: Namespace
metadata:
  name: laddr

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: laddr

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployer
  namespace: laddr
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployer
  namespace: laddr
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: laddr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer
