apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-warehouse.fullname" . }}-postgresql
  labels:
    {{- include "data-warehouse.labels" . | nindent 4 }}
    component: postgresql
spec:
  selector:
    app.kubernetes.io/name: {{ include "data-warehouse.name" . }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
