---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: balancer-db-credentials
  namespace: cloudnative-pg
spec:
  encryptedData:
    password: AgBoGKtydhGjaug2+iATGf+WOKwGTp++12g839Qtdb7ixYJz+7zPRfR+BA3SRLJMME2JdgTR3CuLNo8UhAMd9j6z6ehqpz1w4hOA1/03C7pMvzKYazVwGME+OdUnyQzrlIM8BNjIxpOEi9jS9Xyb8LGSD2dRIw/mbDX8EB5IT/jS9By0eCSRcx7Zz8SPD6dI9eg9hhIVlK1x0JqPeUAfUN0oQzdDh02fayzBi/eOQsh9tYwFBzD3iMOySs/Ax5krGqzn5qBfNa/6ixjuX0r9gRuo7sP19WFtS5okOzoTzAPVNd9uRMJrNxT1VUrfFaEJXcE9WgnNqGPMwEtNW0PiBm4MIfLm6L7Cn2kZ3jzBB49g3x3xIV9YZUgaBQHbnw49KAHHGrON8fM0mOSw1p3RnNSOBbfW6dSOxXEoZwDmmvp3QSY0StwopXcmbOGjm/TS9rp55qpSyquvUTq1gGljCdNyQKVgB82Y30N9jzpztLgDwARK7s7tgdmYH2kpvzA5duLwh8kRwoSS95XVTjWC6qEt1i94PZY8NMObrXLSsDly06YvRWRnuEGTgX8vDjUCOLhHCUGSwYDFeepqW9VEg6UeN+cEdFUAWe6AXXD+wzgHphF7PrLXVtJ44k2OSqtCcC8x8mcxRkF2K4p6XfwuyypBXfvv1opnqn605QAHgJr6b1pFzd8xaXTaIWfona0UzXf+c4Aveo/2wFAS3enU8w6gmNVq6qxyZ+NSwM6Q+fCA4j/zcESyQtlvTHkFPwG/Q3U=
    username: AgCgnAjFX4lJ+XXmrpv5pw0OQLEiEIIf31Q3lzIzI/iSiuYLYTd3k2WBzXcywxS/C0hiNty5Y4yG51ADGDojz/lYJnQJrOgbqQJZ4l/tGqd5Xnu9JLcxuuBdBLw/FCFnxw/SQ0Fs/g9Rk8J6qD1F7qf8SNEIZI2YEA7Y7gE0f5gxyqfen2cbssfLAf2yOWOzvbak++J/qvPZpT9meit+NkjDz0Gk6jfDoAlWiSbtZ1qw0UJ+w5le0tiYsemf9uPguxVRywYfSLtjEKt0oq9guDKgi567sUKKPzgxg/2U/BmszlMznOzj2lJIa/L2ii89bHiiOthDjecZEAKrHjYBvF5XITgKK8jGCepem2AHqvDyx3OsdOEYf4uwJNLsbvKO+N9MeGlU9VIFXY0j06ru24JyKPrdpDJ2bw6I5K3anq4/QTbKVE/Vs+TTm1i0ZIC6CGpRUQdNhkcqcIQWPKZ6xASuJ9eMNYunqZSDmy8Mg0a6meT5vZZnT/Pzg/QiTvKpIukFq7K5q0t9lv3n9tCrsLuNQURu4EWn3OD87nSQW+OOksLwBg65avDn0lVKWi3mlhmbLfjOmlYV+iJSyUyhCdr10HuYWP4b/JKu5TqFLsUxAbtyqnzGA+YCKVuIT310Sxrq3+ooowAlTxVS9uxBAed9z1HoVGUp/UmyKmsQ72wH8bUAepFMXZg5rzEhJhUXEmh2f8sSB49/2w==
  template:
    metadata:
      name: balancer-db-credentials
      namespace: cloudnative-pg
    type: kubernetes.io/basic-auth
